#!/usr/bin/env bash
# Per-boot runtime setup for MKPK Inventaire.
# Brings up Docker + the local Supabase stack, applies the schema, and writes
# .env.local so `next dev` (started via the "next-dev" terminal) can connect.
# Safe to run repeatedly.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

echo "==> Allow container-to-container traffic on the docker bridge"
# On the same docker bridge, packets are L2-switched. When bridge netfilter is
# enabled they are pushed through the FORWARD chain and dropped, which breaks
# Supabase's inter-container connections. Disabling it keeps intra-bridge
# traffic as pure L2 without affecting port publishing or outbound NAT.
sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 >/dev/null 2>&1 || true
sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=0 >/dev/null 2>&1 || true

echo "==> Starting the Docker daemon"
if ! sudo test -S /var/run/docker.sock || ! docker info >/dev/null 2>&1; then
  sudo pkill -x dockerd >/dev/null 2>&1 || true
  sleep 1
  # Log to a root-owned path: a snapshot may preserve a stale, other-owned
  # /tmp/dockerd.log which, under fs.protected_regular, cannot be reopened even
  # by root and would prevent dockerd from launching.
  sudo bash -c 'nohup dockerd >/var/log/dockerd.log 2>&1 &'
  for _ in $(seq 1 30); do
    sudo test -S /var/run/docker.sock && break
    sleep 1
  done
fi
# Make the socket usable without sudo for this dev VM.
sudo chmod 666 /var/run/docker.sock 2>/dev/null || true
# Wait until the daemon actually responds before using it.
for _ in $(seq 1 30); do docker info >/dev/null 2>&1 && break; sleep 1; done
docker version >/dev/null

echo "==> Starting the local Supabase stack (tolerating a cold Docker daemon)"
# On a freshly started daemon the db container can take more than a few seconds
# to become healthy, so retry rather than giving up after one quick attempt.
for attempt in $(seq 1 6); do
  if supabase start; then break; fi
  echo "    supabase start attempt ${attempt} incomplete; waiting for containers..."
  sleep 10
done
# Ensure Postgres is actually accepting connections before touching it.
for _ in $(seq 1 60); do
  pg_isready -h 127.0.0.1 -p 54322 -U postgres >/dev/null 2>&1 && break
  sleep 2
done
pg_isready -h 127.0.0.1 -p 54322 -U postgres >/dev/null

echo "==> Applying database schema"
export PGPASSWORD=postgres
# schema.sql is fully idempotent (IF NOT EXISTS / ON CONFLICT / CREATE OR REPLACE).
psql -h 127.0.0.1 -p 54322 -U postgres -d postgres -v ON_ERROR_STOP=1 -f supabase/schema.sql >/dev/null
echo "    schema applied"

echo "==> Writing .env.local from local Supabase credentials"
eval "$(supabase status -o env | sed 's/^/SB_/')"
cat > .env.local <<EOF
# Generated by .cursor/start.sh — points at the local Supabase stack.
SUPABASE_URL=${SB_API_URL//\"/}
SUPABASE_SERVICE_ROLE_KEY=${SB_SERVICE_ROLE_KEY//\"/}

# Optionnel : mot de passe pour protéger l'accès à l'app
INVENTORY_PASSWORD=

PORT=3000
EOF

echo "==> start.sh complete — app will be served by the 'next-dev' terminal on http://localhost:3000"
